apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuid-nokia-srl
  namespace: kuid-system
  labels:
    app.kubernetes.io/name: kuid-nokia-srl
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kuid-nokia-srl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kuid-nokia-srl
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      serviceAccountName: kuid-nokia-srl
      containers:
      - name: kuid-nokia-srl
        image: europe-docker.pkg.dev/srlinux/eu.gcr.io/kuid-nokia-srl:latest
        imagePullPolicy: Always
        command:
        - /app/nokia-srl
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: "NODE_NAME"
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: "NODE_IP"
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: ENABLE_NODECONFIG
          value: "true"
        - name: ENABLE_DEVICECONFIG
          value: "true"
        volumeMounts:
        - name: gotemplates-volume
          mountPath: /app/templates
          readOnly: true
      volumes:
      - name: gotemplates-volume
        configMap:
          name: gotemplates-srl
