apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: kuid-nokia-srl
  name: kuid-nokia-srl-leader-election-role
  namespace: kuid-system
rules:
- apiGroups: [""]
  resources: [configmaps]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [get, watch, list, create, update, patch, delete]
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch]