apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kuid-nokia-srl
  name: kuid-nokia-srl-leader-election-role-binding
  namespace: kuid-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kuid-nokia-srl-leader-election-role
subjects:
- kind: ServiceAccount
  name: kuid-nokia-srl
  namespace: kuid-system
